module.exports = {
	'wrapper-width':    '1024px',
	'site-width':       '1024px',
	'column-count':     '12',
	'background-color': '#fcfcfc',
	'foreground-color': '#030303',
	'highlight-color':  '#941b0c',
	'border-color':     '#d6d6d6',
	'base-line-height': '1.25',
	'base-font-size':   '16px',
	'small-font-size':  '14px',
	'h6-font-size':     '18px',
	'h5-font-size':     '20px',
	'h4-font-size':     '22px',
	'h3-font-size':     '24px',
	'h2-font-size':     '26px',
	'h1-font-size':     '48px',
};
